//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using System.Linq;
using SimpleJSON;

namespace cfg.error
{
    public sealed partial class TbErrorInfo
    {
        private readonly Dictionary<string, error.ErrorInfo> _dataMap;
        private readonly List<error.ErrorInfo> _dataList;
        
        public TbErrorInfo(JSONNode _json)
        {
            var count = _json.Children.Count();
            _dataMap = new Dictionary<string, error.ErrorInfo>(count);
            _dataList = new List<error.ErrorInfo>(count);
            
            foreach(var _row in _json.Children)
            {
                var _v = error.ErrorInfo.DeserializeErrorInfo(_row);
                _dataList.Add(_v);
                _dataMap.Add(_v.Code, _v);
            }
            PostInit();
        }
    
        public Dictionary<string, error.ErrorInfo> DataMap => _dataMap;
        public List<error.ErrorInfo> DataList => _dataList;
    
        public error.ErrorInfo GetOrDefault(string key)
        {
            return _dataMap.TryGetValue(key, out var v) ? v : null;
        }
        
        public error.ErrorInfo Get(string key)
        {
            return _dataMap[key];
        }
        
        public error.ErrorInfo this[string key]
        {
            get { return _dataMap[key]; }
        }
    
        public void Resolve(Dictionary<string, object> _tables)
        {
            foreach(var v in _dataList)
            {
                v.Resolve(_tables);
            }
            PostResolve();
        }
    
        public void TranslateText(System.Func<string, string, string> translator)
        {
            foreach(var v in _dataList)
            {
                v.TranslateText(translator);
            }
        }
        
        
        partial void PostInit();
        partial void PostResolve();
    }
}