
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using Server.Config.Core;


namespace cfg.l10n
{
public sealed partial class PatchDemo : Server.Config.Core.BeanBase
{
    public PatchDemo(JsonElement _buf) 
    {
        Id = _buf.GetProperty("id").GetInt32();
        Value = _buf.GetProperty("value").GetInt32();
    }

    public static PatchDemo DeserializePatchDemo(JsonElement _buf)
    {
        return new l10n.PatchDemo(_buf);
    }

    public readonly int Id;
    public readonly int Value;
   
    public const int __ID__ = -1707294656;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "value:" + Value + ","
        + "}";
    }
}

}
