
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using GameFrameX.Core.Config;

namespace GameFrameX.Config.Tables
{
    public partial class TbSoundsConfig : BaseDataTable<Tables.SoundsConfig>
    {
        //private readonly System.Collections.Generic.Dictionary<int, Tables.SoundsConfig> _dataMap;
        //private readonly System.Collections.Generic.List<Tables.SoundsConfig> _dataList;
    
        //public System.Collections.Generic.Dictionary<int, Tables.SoundsConfig> DataMap => _dataMap;
        //public System.Collections.Generic.List<Tables.SoundsConfig> DataList => _dataList;
        //public Tables.SoundsConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        //public Tables.SoundsConfig Get(int key) => _dataMap[key];
        //public Tables.SoundsConfig this[int key] => _dataMap[key];
    
        public override async System.Threading.Tasks.Task LoadAsync()
        {
            var jsonElement = await _loadFunc();
            DataList.Clear();
            LongDataMaps.Clear();
            StringDataMaps.Clear();
            foreach(var element in jsonElement.EnumerateArray())
            {
                Tables.SoundsConfig _v;
                _v = Tables.SoundsConfig.DeserializeSoundsConfig(element);
                DataList.Add(_v);
                LongDataMaps.Add(_v.Id, _v);
                StringDataMaps.Add(_v.Id.ToString(), _v);
            }
            PostInit();
        }

        public void ResolveRef(TablesComponent tables)
        {
            foreach(var element in DataList)
            {
                element.ResolveRef(tables);
            }
        }
    
    
        partial void PostInit();

        public TbSoundsConfig(Func<Task<JsonElement>> loadFunc) : base(loadFunc)
        {
        }
    }
}
