using System.Text;

namespace GameFrameX.ProtoExport;

[Mode(ModeType.Lua)]
internal sealed class ProtoBufLuaHelper : IProtoGenerateHelper
{
    private string _importPath = "../network/";
    private bool _shouldGenerateDescription;

    public void Init(LauncherOptions launcherOptions)
    {
        if (!string.IsNullOrEmpty(launcherOptions.ImportPath))
        {
            _importPath = launcherOptions.ImportPath;
        }

        _shouldGenerateDescription = launcherOptions.IsGenerateDescription;
    }

    public void Run(MessageInfoList messageInfoList, string outputPath, string namespaceName)
    {
        StringBuilder sb = new StringBuilder();
        sb.AppendLine("--- Code generated by GameFrameX ProtoExport. Do not edit.");
        sb.AppendLine();
        sb.Append($"local MessageObject = require(\"{_importPath}MessageObject\")\n");
        sb.Append($"local ProtoMessageHelper = require(\"{_importPath}ProtoMessageHelper\")\n");
        sb.Append("\n");

        var moduleName = messageInfoList.ModuleName;

        sb.AppendLine($"local {moduleName} = {{}}");
        sb.AppendLine($"{moduleName}.__index = {moduleName}");
        sb.AppendLine();

        foreach (var operationCodeInfo in messageInfoList.Infos)
        {
            if (operationCodeInfo.IsEnum)
            {
                AppendEnum(sb, moduleName, operationCodeInfo);
            }
            else
            {
                AppendMessage(sb, moduleName, messageInfoList, operationCodeInfo);
            }
        }

        sb.AppendLine($"return {moduleName}");
        ExportLogger.WriteLine($"Generate File:{messageInfoList.OutputPath + ".lua"}");
        File.WriteAllText(messageInfoList.OutputPath + ".lua", sb.ToString(), Encoding.UTF8);
    }

    private void AppendEnum(StringBuilder sb, string moduleName, MessageInfo operationCodeInfo)
    {
        if (_shouldGenerateDescription && !string.IsNullOrEmpty(operationCodeInfo.Description))
        {
            sb.AppendLine($"--- {operationCodeInfo.Description}");
        }

        sb.AppendLine($"---@enum {moduleName}.{operationCodeInfo.Name}");
        sb.AppendLine($"{moduleName}.{operationCodeInfo.Name} = {{");

        foreach (var operationField in operationCodeInfo.Fields)
        {
            if (string.IsNullOrEmpty(operationField.Type))
            {
                continue;
            }

            var desc = string.IsNullOrEmpty(operationField.Description) ? "" : $" {operationField.Description}";
            sb.AppendLine($"\t{operationField.Type} = {operationField.Members}, ---@type number{desc}");
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    private void AppendMessage(StringBuilder sb, string moduleName, MessageInfoList messageInfoList, MessageInfo operationCodeInfo)
    {
        if (_shouldGenerateDescription && !string.IsNullOrEmpty(operationCodeInfo.Description))
        {
            sb.AppendLine($"--- {operationCodeInfo.Description}");
        }

        var className = $"{moduleName}.{operationCodeInfo.Name}";

        if (string.IsNullOrEmpty(operationCodeInfo.ParentClass))
        {
            sb.AppendLine($"---@class {className}");
        }
        else
        {
            sb.AppendLine($"---@class {className} : MessageObject");
        }

        foreach (var operationField in operationCodeInfo.Fields)
        {
            if (!operationField.IsValid)
            {
                continue;
            }

            var luaType = TypeMapper.ToLua(operationField.Type);
            if (operationField.IsRepeated)
            {
                luaType = $"{TypeMapper.ToLua(operationField.Type)}[]";
            }

            var desc = string.IsNullOrEmpty(operationField.Description) ? "" : $" {operationField.Description}";
            sb.AppendLine($"---@field {operationField.Name} {luaType}{desc}");
        }

        sb.AppendLine($"{className} = {{}}");
        sb.AppendLine($"{className}.__index = {className}");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(operationCodeInfo.ParentClass))
        {
            sb.AppendLine($"function {className}.new()");
            sb.AppendLine($"\tlocal self = setmetatable({{}}, {className})");
            sb.AppendLine($"\treturn self");
            sb.AppendLine("end");
            sb.AppendLine();

            sb.AppendLine($"function {className}:register()");
            if (operationCodeInfo.IsRequest)
            {
                sb.AppendLine($"\tProtoMessageHelper.registerReqMessage('{moduleName}.{operationCodeInfo.Name}', {(messageInfoList.Module << 16) + operationCodeInfo.Opcode})");
            }
            else if (operationCodeInfo.IsNotify)
            {
                sb.AppendLine($"\tProtoMessageHelper.registerNotifyMessage('{moduleName}.{operationCodeInfo.Name}', {(messageInfoList.Module << 16) + operationCodeInfo.Opcode})");
            }
            else
            {
                sb.AppendLine($"\tProtoMessageHelper.registerRespMessage('{moduleName}.{operationCodeInfo.Name}', {(messageInfoList.Module << 16) + operationCodeInfo.Opcode})");
            }

            sb.AppendLine("end");
            sb.AppendLine();
        }
    }

    public void Post(List<MessageInfoList> operationCodeInfo, LauncherOptions launcherOptions)
    {
        StringBuilder sb = new StringBuilder();
        sb.AppendLine("--- Code generated by GameFrameX ProtoExport. Do not edit.");
        sb.AppendLine();

        foreach (var messageInfoList in operationCodeInfo)
        {
            sb.AppendLine($"local {messageInfoList.ModuleName} = require(\"{launcherOptions.ImportPath}{messageInfoList.FileName}\")");
        }

        sb.AppendLine();
        sb.AppendLine("local ProtoMessageRegister = {}");
        sb.AppendLine();
        sb.AppendLine("function ProtoMessageRegister.register()");

        foreach (var messageInfoList in operationCodeInfo)
        {
            foreach (var messageInfo in messageInfoList.Infos)
            {
                if (!string.IsNullOrEmpty(messageInfo.ParentClass))
                {
                    sb.AppendLine($"\t{messageInfoList.ModuleName}.{messageInfo.Name}:register()");
                }
            }
        }

        sb.AppendLine("end");
        sb.AppendLine();
        sb.AppendLine("return ProtoMessageRegister");
        ExportLogger.WriteLine($"Generate File:{launcherOptions.OutputPath + "/ProtoMessageRegister.lua"}");
        File.WriteAllText(launcherOptions.OutputPath + "/ProtoMessageRegister.lua", sb.ToString(), Encoding.UTF8);
    }
}
