using System.Text;

namespace GameFrameX.ProtoExport;

[Mode(ModeType.Go)]
internal sealed class ProtoBufGoHelper : IProtoGenerateHelper
{
    private string[] _importStatements = [];
    private bool _shouldGenerateDescription;
    private string _packageName = "proto";

    public void Init(LauncherOptions launcherOptions)
    {
        if (!string.IsNullOrEmpty(launcherOptions.UsingStatements))
        {
            _importStatements = launcherOptions.UsingStatements.Split('|', StringSplitOptions.RemoveEmptyEntries);
        }

        _shouldGenerateDescription = launcherOptions.IsGenerateDescription;

        if (!string.IsNullOrEmpty(launcherOptions.NamespaceName))
        {
            _packageName = launcherOptions.NamespaceName;
            if (_packageName.Contains('.'))
            {
                _packageName = _packageName.Split('.', StringSplitOptions.RemoveEmptyEntries).Last();
            }
        }
    }

    public void Run(MessageInfoList messageInfoList, string outputPath, string namespaceName = "GFXHotfix")
    {
        StringBuilder sb = new StringBuilder();
        sb.AppendLine("// Code generated by GameFrameX ProtoExport. Do not edit.");
        sb.AppendLine();
        sb.AppendLine($"package {_packageName}");
        sb.AppendLine();

        if (_importStatements.Length > 0)
        {
            sb.AppendLine("import (");
            foreach (var import in _importStatements)
            {
                var trimmed = import.Trim().Trim('"');
                sb.AppendLine($"\t\"{trimmed}\"");
            }

            sb.AppendLine(")");
            sb.AppendLine();
        }

        foreach (var operationCodeInfo in messageInfoList.Infos)
        {
            if (operationCodeInfo.IsEnum)
            {
                AppendEnum(sb, operationCodeInfo);
            }
            else
            {
                AppendMessage(sb, messageInfoList, operationCodeInfo);
            }
        }

        ExportLogger.WriteLine($"Generate File:{messageInfoList.OutputPath + ".go"}");
        File.WriteAllText(messageInfoList.OutputPath + ".go", sb.ToString(), Encoding.UTF8);
    }

    private void AppendEnum(StringBuilder sb, MessageInfo operationCodeInfo)
    {
        sb.AppendLine($"// {operationCodeInfo.Description}");
        sb.AppendLine($"type {operationCodeInfo.Name} int32");
        sb.AppendLine();

        sb.AppendLine("const (");
        for (var index = 0; index < operationCodeInfo.Fields.Count; index++)
        {
            var operationField = operationCodeInfo.Fields[index];
            if (string.IsNullOrEmpty(operationField.Type))
            {
                continue;
            }

            var desc = string.IsNullOrEmpty(operationField.Description) ? "" : $" // {operationField.Description}";
            sb.AppendLine($"\t{operationCodeInfo.Name}_{operationField.Type} {operationCodeInfo.Name} = {operationField.Members}{desc}");
        }

        sb.AppendLine(")");
        sb.AppendLine();
    }

    private void AppendMessage(StringBuilder sb, MessageInfoList messageInfoList, MessageInfo operationCodeInfo)
    {
        sb.AppendLine($"// {operationCodeInfo.Description}");

        if (string.IsNullOrEmpty(operationCodeInfo.ParentClass))
        {
            sb.AppendLine($"type {operationCodeInfo.Name} struct {{");
        }
        else
        {
            sb.AppendLine($"type {operationCodeInfo.Name} struct {{");
        }

        for (var index = 0; index < operationCodeInfo.Fields.Count; index++)
        {
            var operationField = operationCodeInfo.Fields[index];
            if (!operationField.IsValid)
            {
                continue;
            }

            var desc = string.IsNullOrEmpty(operationField.Description) ? "" : $" // {operationField.Description}";

            if (operationField.IsRepeated)
            {
                var mappedType = TypeMapper.ToGo(operationField.Type);
                sb.AppendLine($"\t{operationField.Name} []{mappedType} `protobuf:\"varint,{operationField.Members},rep,name={operationField.Name},proto3\" json:\"{operationField.Name},omitempty\"`{desc}");
            }
            else if (operationField.IsKv)
            {
                var mappedType = TypeMapper.ToGo(operationField.Type);
                sb.AppendLine($"\t{operationField.Name} {mappedType} `protobuf:\"bytes,{operationField.Members},opt,name={operationField.Name},proto3\" json:\"{operationField.Name},omitempty\"`{desc}");
            }
            else
            {
                var goType = TypeMapper.ToGo(operationField.Type);
                var protoTag = GetGoProtoTag(operationField.Type, operationField.Members, operationField.Name);
                sb.AppendLine($"\t{operationField.Name} {goType} {protoTag}{desc}");
            }
        }

        sb.AppendLine("}");

        if (!string.IsNullOrEmpty(operationCodeInfo.ParentClass))
        {
            sb.AppendLine();
            sb.AppendLine($"const {operationCodeInfo.Name}_MessageID uint32 = (({messageInfoList.Module}) << 16) + {operationCodeInfo.Opcode}");
        }

        sb.AppendLine();
    }

    private static string GetGoProtoTag(string protoType, int fieldNumber, string fieldName)
    {
        var wireType = protoType switch
        {
            "int32" or "sint32" or "sfixed32" or "int64" or "sint64" or "sfixed64" or "uint32" or "fixed32" or "uint64" or "fixed64" or "bool" or "enum" => "varint",
            "float" => "fixed32",
            "double" => "fixed64",
            "string" or "bytes" => "bytes",
            _ => "bytes",
        };

        return $"`protobuf:\"{wireType},{fieldNumber},opt,name={fieldName},proto3\" json:\"{fieldName},omitempty\"`";
    }

    public void Post(List<MessageInfoList> operationCodeInfo, LauncherOptions launcherOptions)
    {
        StringBuilder sb = new StringBuilder();
        sb.AppendLine("// Code generated by GameFrameX ProtoExport. Do not edit.");
        sb.AppendLine();
        sb.AppendLine($"package {_packageName}");
        sb.AppendLine();

        var hasImports = false;
        foreach (var messageInfoList in operationCodeInfo)
        {
            foreach (var messageInfo in messageInfoList.Infos)
            {
                if (!string.IsNullOrEmpty(messageInfo.ParentClass))
                {
                    hasImports = true;
                    break;
                }
            }

            if (hasImports) break;
        }

        if (hasImports)
        {
            sb.AppendLine("import (");
            foreach (var messageInfoList in operationCodeInfo)
            {
                sb.AppendLine($"\t\"{launcherOptions.NamespaceName ?? "proto"}/{messageInfoList.ModuleName}_{messageInfoList.Module}\"");
            }

            sb.AppendLine(")");
            sb.AppendLine();
        }

        sb.AppendLine("// RegisterAllMessages registers all proto messages");
        sb.AppendLine("func RegisterAllMessages() {");
        foreach (var messageInfoList in operationCodeInfo)
        {
            foreach (var messageInfo in messageInfoList.Infos)
            {
                if (!string.IsNullOrEmpty(messageInfo.ParentClass))
                {
                    sb.AppendLine($"\t// {messageInfoList.ModuleName}_{messageInfoList.Module}.{messageInfo.Name}: MessageID = {(messageInfoList.Module << 16) + messageInfo.Opcode}");
                }
            }
        }

        sb.AppendLine("}");

        ExportLogger.WriteLine($"Generate File:{launcherOptions.OutputPath + "/message_register.go"}");
        File.WriteAllText(launcherOptions.OutputPath + "/message_register.go", sb.ToString(), Encoding.UTF8);
    }
}
