
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using GameFrameX.Core.Config;

namespace GameFrameX.Config
{
    /// <summary>
    /// 属性
    /// </summary>
    public sealed partial class Property : BeanBase
    {
        /*
        public Property(int PhysicalAttack, int MagicAttack, int PhysicalDefense, int MagicDefense, int Life, int Crit, int BurstDamage, int Precise, int Block) 
        {
            this.PhysicalAttack = PhysicalAttack;
            this.MagicAttack = MagicAttack;
            this.PhysicalDefense = PhysicalDefense;
            this.MagicDefense = MagicDefense;
            this.Life = Life;
            this.Crit = Crit;
            this.BurstDamage = BurstDamage;
            this.Precise = Precise;
            this.Block = Block;
            PostInit();
        }        
        */

        public Property(JsonElement _buf) 
        {
            PhysicalAttack = _buf.GetProperty("PhysicalAttack").GetInt32();
            MagicAttack = _buf.GetProperty("MagicAttack").GetInt32();
            PhysicalDefense = _buf.GetProperty("PhysicalDefense").GetInt32();
            MagicDefense = _buf.GetProperty("MagicDefense").GetInt32();
            Life = _buf.GetProperty("Life").GetInt32();
            Crit = _buf.GetProperty("Crit").GetInt32();
            BurstDamage = _buf.GetProperty("burstDamage").GetInt32();
            Precise = _buf.GetProperty("precise").GetInt32();
            Block = _buf.GetProperty("block").GetInt32();
        }
    
        public static Property DeserializeProperty(JsonElement _buf)
        {
            return new Property(_buf);
        }

        /// <summary>
        /// 物理攻击
        /// </summary>
        public int PhysicalAttack { private set; get; }
        /// <summary>
        /// 魔法攻击
        /// </summary>
        public int MagicAttack { private set; get; }
        /// <summary>
        /// 物理防御
        /// </summary>
        public int PhysicalDefense { private set; get; }
        /// <summary>
        /// 魔法防御
        /// </summary>
        public int MagicDefense { private set; get; }
        /// <summary>
        /// 生命值
        /// </summary>
        public int Life { private set; get; }
        /// <summary>
        /// 暴击
        /// </summary>
        public int Crit { private set; get; }
        /// <summary>
        /// 爆伤
        /// </summary>
        public int BurstDamage { private set; get; }
        /// <summary>
        /// 精准
        /// </summary>
        public int Precise { private set; get; }
        /// <summary>
        /// 格挡
        /// </summary>
        public int Block { private set; get; }

        private const int __ID__ = -928497163;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "PhysicalAttack:" + PhysicalAttack + ","
            + "MagicAttack:" + MagicAttack + ","
            + "PhysicalDefense:" + PhysicalDefense + ","
            + "MagicDefense:" + MagicDefense + ","
            + "Life:" + Life + ","
            + "Crit:" + Crit + ","
            + "burstDamage:" + BurstDamage + ","
            + "precise:" + Precise + ","
            + "block:" + Block + ","
            + "}";
        }

        partial void PostInit();
    }
}
