
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using GameFrameX.Core.Config;

namespace GameFrameX.Config
{
    public sealed partial class PropItem : BeanBase
    {
        /*
        public PropItem(int Id, int Count) 
        {
            this.Id = Id;
            this.Count = Count;
            PostInit();
        }        
        */

        public PropItem(JsonElement _buf) 
        {
            Id = _buf.GetProperty("Id").GetInt32();
            Count = _buf.GetProperty("Count").GetInt32();
        }
    
        public static PropItem DeserializePropItem(JsonElement _buf)
        {
            return new PropItem(_buf);
        }

        /// <summary>
        /// 道具id
        /// </summary>
        public int Id { private set; get; }
        /// <summary>
        /// 道具数量
        /// </summary>
        public int Count { private set; get; }

        private const int __ID__ = -929329866;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Count:" + Count + ","
            + "}";
        }

        partial void PostInit();
    }
}
