syntax = "proto3";
package InnerSocial;
option module = -120;

// 请求添加好友
message ReqInnerFriendByAdd
{
  int64 PlayerId = 1; // 玩家ID
}

// 响应添加好友
message RespInnerFriendByAdd
{
  bool Success = 1; // 是否成功
}

// 内部好友信息
message InnerFriendInfo
{
  int64 PlayerId = 1; // 玩家ID
  string PlayerName = 2; // 玩家名称
}

// 请求删除好友
message ReqInnerFriendByDelete
{
  int64 PlayerId = 1; // 玩家ID
}

// 响应删除好友
message RespInnerFriendByDelete
{
  bool Success = 1; // 是否成功
}

// 请求好友列表
message ReqInnerFriendList
{
  int64 PlayerId = 1; // 玩家ID
}

// 响应好友列表
message RespInnerFriendList
{
  repeated InnerFriendInfo Friends = 1; // 好友列表
}
