syntax = "proto3";
package Social;
option module = 120;

// 好友信息
message FriendInfo
{
  int64 PlayerId = 1; // 玩家ID
  string PlayerName = 2; // 玩家名称
}

// 请求社交信息
message ReqSocialInfo
{
}

// 响应社交信息
message RespSocialInfo
{
}

// 请求删除好友
message ReqDeleteFriend
{
  int64 PlayerId = 1; // 玩家ID
}

// 响应删除好友
message RespDeleteFriend
{
  bool Success = 1; // 是否成功
}

// 请求好友列表
message ReqFriendList
{
}

// 响应好友列表
message RespFriendList
{
  repeated FriendInfo Friends = 1; // 好友列表
}

// 请求添加好友
message ReqFriendByAdd
{
  int64 PlayerId = 1; // 玩家ID
}

// 响应添加好友
message RespFriendByAdd
{
  bool Success = 1; // 是否成功
}
