
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LuBan.Runtime;
using GameFrameX.Config;
using SimpleJSON;

namespace Hotfix.Config.Local
{
    public sealed partial class Localization : LuBan.Runtime.BeanBase
    {
        public Localization(string Key, string ChineseSimplified, string ChineseTraditional, string English, string Japanese, string Korean, string Thai, string Indonesian, string French, string German, string Russian, string Italian, string PortuguesePortugal, string Spanish, string Vietnamese) 
        {
            this.Key = Key;
            this.ChineseSimplified = ChineseSimplified;
            this.ChineseTraditional = ChineseTraditional;
            this.English = English;
            this.Japanese = Japanese;
            this.Korean = Korean;
            this.Thai = Thai;
            this.Indonesian = Indonesian;
            this.French = French;
            this.German = German;
            this.Russian = Russian;
            this.Italian = Italian;
            this.PortuguesePortugal = PortuguesePortugal;
            this.Spanish = Spanish;
            this.Vietnamese = Vietnamese;
            PostInit();
        }

        public Localization(JSONNode _buf)
        {
            { if(!_buf["key"].IsString) { throw new SerializationException(); }  Key = _buf["key"]; }
            { if(!_buf["ChineseSimplified"].IsString) { throw new SerializationException(); }  ChineseSimplified = _buf["ChineseSimplified"]; }
            { if(!_buf["ChineseTraditional"].IsString) { throw new SerializationException(); }  ChineseTraditional = _buf["ChineseTraditional"]; }
            { if(!_buf["English"].IsString) { throw new SerializationException(); }  English = _buf["English"]; }
            { if(!_buf["Japanese"].IsString) { throw new SerializationException(); }  Japanese = _buf["Japanese"]; }
            { if(!_buf["Korean"].IsString) { throw new SerializationException(); }  Korean = _buf["Korean"]; }
            { if(!_buf["Thai"].IsString) { throw new SerializationException(); }  Thai = _buf["Thai"]; }
            { if(!_buf["Indonesian"].IsString) { throw new SerializationException(); }  Indonesian = _buf["Indonesian"]; }
            { if(!_buf["French"].IsString) { throw new SerializationException(); }  French = _buf["French"]; }
            { if(!_buf["German"].IsString) { throw new SerializationException(); }  German = _buf["German"]; }
            { if(!_buf["Russian"].IsString) { throw new SerializationException(); }  Russian = _buf["Russian"]; }
            { if(!_buf["Italian"].IsString) { throw new SerializationException(); }  Italian = _buf["Italian"]; }
            { if(!_buf["PortuguesePortugal"].IsString) { throw new SerializationException(); }  PortuguesePortugal = _buf["PortuguesePortugal"]; }
            { if(!_buf["Spanish"].IsString) { throw new SerializationException(); }  Spanish = _buf["Spanish"]; }
            { if(!_buf["Vietnamese"].IsString) { throw new SerializationException(); }  Vietnamese = _buf["Vietnamese"]; }

            // Localization Key Begin
            // Localization Key End
            PostInit();
        }

        public static Localization DeserializeLocalization(JSONNode _buf)
        {
            return new Local.Localization(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public string Key { private set; get; }
        /// <summary>
        /// 简体中心
        /// </summary>
        public string ChineseSimplified { private set; get; }
        /// <summary>
        /// 繁体中心
        /// </summary>
        public string ChineseTraditional { private set; get; }
        /// <summary>
        /// 英语
        /// </summary>
        public string English { private set; get; }
        /// <summary>
        /// 日语
        /// </summary>
        public string Japanese { private set; get; }
        /// <summary>
        /// 韩语
        /// </summary>
        public string Korean { private set; get; }
        /// <summary>
        /// 泰语
        /// </summary>
        public string Thai { private set; get; }
        /// <summary>
        /// 印尼语
        /// </summary>
        public string Indonesian { private set; get; }
        /// <summary>
        /// 法语
        /// </summary>
        public string French { private set; get; }
        /// <summary>
        /// 德语
        /// </summary>
        public string German { private set; get; }
        /// <summary>
        /// 俄语
        /// </summary>
        public string Russian { private set; get; }
        /// <summary>
        /// 意大利语
        /// </summary>
        public string Italian { private set; get; }
        /// <summary>
        /// 葡萄牙语
        /// </summary>
        public string PortuguesePortugal { private set; get; }
        /// <summary>
        /// 西班牙语
        /// </summary>
        public string Spanish { private set; get; }
        /// <summary>
        /// 越南语
        /// </summary>
        public string Vietnamese { private set; get; }
        public const int __ID__ = -1694250884;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
        }

        public void TranslateText(System.Func<string, string, string> translator)
        {
        }

        public override string ToString()
        {
            return "{ "
            + "key:" + Key + ","
            + "ChineseSimplified:" + ChineseSimplified + ","
            + "ChineseTraditional:" + ChineseTraditional + ","
            + "English:" + English + ","
            + "Japanese:" + Japanese + ","
            + "Korean:" + Korean + ","
            + "Thai:" + Thai + ","
            + "Indonesian:" + Indonesian + ","
            + "French:" + French + ","
            + "German:" + German + ","
            + "Russian:" + Russian + ","
            + "Italian:" + Italian + ","
            + "PortuguesePortugal:" + PortuguesePortugal + ","
            + "Spanish:" + Spanish + ","
            + "Vietnamese:" + Vietnamese + ","
            + "}";
        }

        partial void PostInit();
    }
}
