
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LuBan.Runtime;
using GameFrameX.Config.Runtime;
using SimpleJSON;


namespace Hotfix.Config.Local
{
    public partial class TbLocalization : BaseDataTable<Local.Localization>
    {
        private readonly System.Func<System.Threading.Tasks.Task<JSONNode>> _loadFunc;        
        public TbLocalization(System.Func<System.Threading.Tasks.Task<JSONNode>> loadFunc)
        {
            _loadFunc = loadFunc;
        }
        public override async System.Threading.Tasks.Task LoadAsync()
        {
            var jsonNode = await _loadFunc();
            StringDataMaps.Clear();
            DataList.Clear();
            foreach(var _ele in jsonNode.Children)
            {
                Local.Localization _v;
                { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Local.Localization.DeserializeLocalization(_ele);  }
                DataList.Add(_v);
                StringDataMaps.Add(_v.Key.ToString(), _v);
            }
            PostInit();
        }
    
        public void ResolveRef(TablesComponent tables)
        {
            foreach(var value in DataList)
            {
                value.ResolveRef(tables);
            }
        }

        public void TranslateText(System.Func<string, string, string> translator)
        {
            foreach(var v in DataList)
            {
                v.TranslateText(translator);
            }
        }




        partial void PostInit();
    }
}

