
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using GameFrameX.Core.Config;

namespace GameFrameX.Config.Local
{
    public sealed partial class Localization : BeanBase
    {
        /*
        public Localization(string Key, string ChineseSimplified, string ChineseTraditional, string English, string Japanese, string Korean, string Thai, string Indonesian, string French, string German, string Russian, string Italian, string PortuguesePortugal, string Spanish, string Vietnamese) 
        {
            this.Key = Key;
            this.ChineseSimplified = ChineseSimplified;
            this.ChineseTraditional = ChineseTraditional;
            this.English = English;
            this.Japanese = Japanese;
            this.Korean = Korean;
            this.Thai = Thai;
            this.Indonesian = Indonesian;
            this.French = French;
            this.German = German;
            this.Russian = Russian;
            this.Italian = Italian;
            this.PortuguesePortugal = PortuguesePortugal;
            this.Spanish = Spanish;
            this.Vietnamese = Vietnamese;
            PostInit();
        }        
        */

        public Localization(JsonElement _buf) 
        {
            Key = _buf.GetProperty("key").GetString();
            ChineseSimplified = _buf.GetProperty("ChineseSimplified").GetString();
            ChineseTraditional = _buf.GetProperty("ChineseTraditional").GetString();
            English = _buf.GetProperty("English").GetString();
            Japanese = _buf.GetProperty("Japanese").GetString();
            Korean = _buf.GetProperty("Korean").GetString();
            Thai = _buf.GetProperty("Thai").GetString();
            Indonesian = _buf.GetProperty("Indonesian").GetString();
            French = _buf.GetProperty("French").GetString();
            German = _buf.GetProperty("German").GetString();
            Russian = _buf.GetProperty("Russian").GetString();
            Italian = _buf.GetProperty("Italian").GetString();
            PortuguesePortugal = _buf.GetProperty("PortuguesePortugal").GetString();
            Spanish = _buf.GetProperty("Spanish").GetString();
            Vietnamese = _buf.GetProperty("Vietnamese").GetString();
        }
    
        public static Localization DeserializeLocalization(JsonElement _buf)
        {
            return new Local.Localization(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public string Key { private set; get; }
        /// <summary>
        /// 简体中心
        /// </summary>
        public string ChineseSimplified { private set; get; }
        /// <summary>
        /// 繁体中心
        /// </summary>
        public string ChineseTraditional { private set; get; }
        /// <summary>
        /// 英语
        /// </summary>
        public string English { private set; get; }
        /// <summary>
        /// 日语
        /// </summary>
        public string Japanese { private set; get; }
        /// <summary>
        /// 韩语
        /// </summary>
        public string Korean { private set; get; }
        /// <summary>
        /// 泰语
        /// </summary>
        public string Thai { private set; get; }
        /// <summary>
        /// 印尼语
        /// </summary>
        public string Indonesian { private set; get; }
        /// <summary>
        /// 法语
        /// </summary>
        public string French { private set; get; }
        /// <summary>
        /// 德语
        /// </summary>
        public string German { private set; get; }
        /// <summary>
        /// 俄语
        /// </summary>
        public string Russian { private set; get; }
        /// <summary>
        /// 意大利语
        /// </summary>
        public string Italian { private set; get; }
        /// <summary>
        /// 葡萄牙语
        /// </summary>
        public string PortuguesePortugal { private set; get; }
        /// <summary>
        /// 西班牙语
        /// </summary>
        public string Spanish { private set; get; }
        /// <summary>
        /// 越南语
        /// </summary>
        public string Vietnamese { private set; get; }

        private const int __ID__ = -1694250884;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "key:" + Key + ","
            + "ChineseSimplified:" + ChineseSimplified + ","
            + "ChineseTraditional:" + ChineseTraditional + ","
            + "English:" + English + ","
            + "Japanese:" + Japanese + ","
            + "Korean:" + Korean + ","
            + "Thai:" + Thai + ","
            + "Indonesian:" + Indonesian + ","
            + "French:" + French + ","
            + "German:" + German + ","
            + "Russian:" + Russian + ","
            + "Italian:" + Italian + ","
            + "PortuguesePortugal:" + PortuguesePortugal + ","
            + "Spanish:" + Spanish + ","
            + "Vietnamese:" + Vietnamese + ","
            + "}";
        }

        partial void PostInit();
    }
}
