
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LuBan.Runtime;
using SimpleJSON;


namespace cfg.ai
{
    public partial class TbBehaviorTree
    {
        private readonly System.Collections.Generic.Dictionary<int, ai.BehaviorTree> _dataMap;
        private readonly System.Collections.Generic.List<ai.BehaviorTree> _dataList;
        
        public TbBehaviorTree(JSONNode jsonNode)
        {
            _dataMap = new System.Collections.Generic.Dictionary<int, ai.BehaviorTree>();
            _dataList = new System.Collections.Generic.List<ai.BehaviorTree>();
            
            foreach(JSONNode vNode in jsonNode.Children)
            {
                ai.BehaviorTree deserializeItem;
                { if(!vNode.IsObject) { throw new SerializationException(); }  deserializeItem = ai.BehaviorTree.DeserializeBehaviorTree(vNode);  }
                _dataList.Add(deserializeItem);
                _dataMap.Add(deserializeItem.Id, deserializeItem);
            }
        }
    
        public System.Collections.Generic.Dictionary<int, ai.BehaviorTree> DataMap 
        {
            get { return _dataMap; }
        }

        public System.Collections.Generic.List<ai.BehaviorTree> DataList 
        {
            get { return _dataList; }
        }
    
        public ai.BehaviorTree GetOrDefault(int key) 
        {  
            return _dataMap.TryGetValue(key, out var v) ? v : null;
        }
        
        public ai.BehaviorTree Get(int key) 
        { 
            return _dataMap[key];
        }
        
        public ai.BehaviorTree this[int key] 
        {
            get
            {
                return _dataMap[key];
            }
        }
    
        public void ResolveRef(Tables tables)
        {
            foreach(var value in _dataList)
            {
                value.ResolveRef(tables);
            }
        }
        
    }

}
