
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LuBan.Runtime;
using SimpleJSON;


namespace cfg.ai
{
    public partial class TbBlackboard
    {
        private readonly System.Collections.Generic.Dictionary<string, ai.Blackboard> _dataMap;
        private readonly System.Collections.Generic.List<ai.Blackboard> _dataList;
        
        public TbBlackboard(JSONNode jsonNode)
        {
            _dataMap = new System.Collections.Generic.Dictionary<string, ai.Blackboard>();
            _dataList = new System.Collections.Generic.List<ai.Blackboard>();
            
            foreach(JSONNode vNode in jsonNode.Children)
            {
                ai.Blackboard deserializeItem;
                { if(!vNode.IsObject) { throw new SerializationException(); }  deserializeItem = ai.Blackboard.DeserializeBlackboard(vNode);  }
                _dataList.Add(deserializeItem);
                _dataMap.Add(deserializeItem.Name, deserializeItem);
            }
        }
    
        public System.Collections.Generic.Dictionary<string, ai.Blackboard> DataMap 
        {
            get { return _dataMap; }
        }

        public System.Collections.Generic.List<ai.Blackboard> DataList 
        {
            get { return _dataList; }
        }
    
        public ai.Blackboard GetOrDefault(string key) 
        {  
            return _dataMap.TryGetValue(key, out var v) ? v : null;
        }
        
        public ai.Blackboard Get(string key) 
        { 
            return _dataMap[key];
        }
        
        public ai.Blackboard this[string key] 
        {
            get
            {
                return _dataMap[key];
            }
        }
    
        public void ResolveRef(Tables tables)
        {
            foreach(var value in _dataList)
            {
                value.ResolveRef(tables);
            }
        }
        
    }

}
