
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Hotfix.Config
{ 
    public enum GiftModelType
    {
        /// <summary>
        /// 不可预览
        /// </summary>
        Non = 0,
        /// <summary>
        /// 单一预览
        /// </summary>
        Single = 1,
        /// <summary>
        /// 整套预览
        /// </summary>
        Complete = 2,
        /// <summary>
        /// 分开预览
        /// </summary>
        Enumeration = 3,
        /// <summary>
        /// 组合预览
        /// </summary>
        Combination = 4,
    }

} 

