
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Hotfix.Config
{ 
    public enum GiftUIType
    {
        /// <summary>
        /// 普通界面
        /// </summary>
        Normal = 0,
        /// <summary>
        /// 特殊界面
        /// </summary>
        Style_1 = 1,
    }

} 

