
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Hotfix.Config
{ 
    public enum GiftFilterType
    {
        /// <summary>
        /// 无，全部获得
        /// </summary>
        None = 0,
        /// <summary>
        /// 随机获得N件
        /// </summary>
        Random = 1,
        /// <summary>
        /// 自定义选择N件
        /// </summary>
        Custom = 2,
    }

} 

