
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Hotfix.Config
{ 
    public enum ItemEPrompt
    {
        /// <summary>
        /// 否
        /// </summary>
        NONE = 0,
        /// <summary>
        /// 新装备
        /// </summary>
        NEW_EQUIP = 1,
        /// <summary>
        /// 红点
        /// </summary>
        RED_POINT = 2,
    }

} 

