
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Hotfix.Config
{ 
    public enum ItemCanUse
    {
        /// <summary>
        /// 不能使用
        /// </summary>
        CanNot = 0,
        /// <summary>
        /// 只能单个使用
        /// </summary>
        UseOne = 1,
        /// <summary>
        /// 可以一键使用全部
        /// </summary>
        UseTotal = 2,
    }

} 

