
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Hotfix.Config
{ 
    public enum ItemLevelColor
    {
        /// <summary>
        /// 蓝色
        /// </summary>
        B = 0,
        /// <summary>
        /// 紫色
        /// </summary>
        A = 1,
        /// <summary>
        /// 橙色
        /// </summary>
        S = 2,
        /// <summary>
        /// 红色
        /// </summary>
        SR = 3,
        /// <summary>
        /// 金色
        /// </summary>
        SSR = 4,
    }

} 

