
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LuBan.Runtime;
using SimpleJSON;


namespace cfg.item
{
    /// <summary>
    /// 道具表
    /// </summary>
    public partial class TbItem
    {
        private readonly System.Collections.Generic.Dictionary<int, item.Item> _dataMap;
        private readonly System.Collections.Generic.List<item.Item> _dataList;
        
        public TbItem(JSONNode jsonNode)
        {
            _dataMap = new System.Collections.Generic.Dictionary<int, item.Item>();
            _dataList = new System.Collections.Generic.List<item.Item>();
            
            foreach(JSONNode vNode in jsonNode.Children)
            {
                item.Item deserializeItem;
                { if(!vNode.IsObject) { throw new SerializationException(); }  deserializeItem = item.Item.DeserializeItem(vNode);  }
                _dataList.Add(deserializeItem);
                _dataMap.Add(deserializeItem.Id, deserializeItem);
            }
        }
    
        public System.Collections.Generic.Dictionary<int, item.Item> DataMap 
        {
            get { return _dataMap; }
        }

        public System.Collections.Generic.List<item.Item> DataList 
        {
            get { return _dataList; }
        }
    
        public item.Item GetOrDefault(int key) 
        {  
            return _dataMap.TryGetValue(key, out var v) ? v : null;
        }
        
        public item.Item Get(int key) 
        { 
            return _dataMap[key];
        }
        
        public item.Item this[int key] 
        {
            get
            {
                return _dataMap[key];
            }
        }
    
        public void ResolveRef(Tables tables)
        {
            foreach(var value in _dataList)
            {
                value.ResolveRef(tables);
            }
        }
        
    }

}
