
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Hotfix.Config
{ 
    public enum ItemUseLimiteType
    {
        /// <summary>
        /// 无限制
        /// </summary>
        NOLIMITE = 0,
        /// <summary>
        /// 日限制
        /// </summary>
        DAYLIMITE = 1,
        /// <summary>
        /// vip限制
        /// </summary>
        VIPLIMITE = 2,
        /// <summary>
        /// 周限制
        /// </summary>
        WEEK6LIMITE = 3,
    }

} 

