
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Hotfix.Config
{ 
    public enum ItemSubType
    {
        /// <summary>
        /// 无
        /// </summary>
        NONE = 0,
        /// <summary>
        /// 武器
        /// </summary>
        WEAPON = 1,
        /// <summary>
        /// 胸
        /// </summary>
        CHEST = 2,
        /// <summary>
        /// 腰带
        /// </summary>
        BELT = 3,
        /// <summary>
        /// 鞋子
        /// </summary>
        BOOT = 4,
        /// <summary>
        /// 戒指
        /// </summary>
        RING = 5,
    }

} 

