
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Hotfix.Config
{ 
    public enum ItemType
    {
        /// <summary>
        /// 道具
        /// </summary>
        Item = 0,
        /// <summary>
        /// 消耗品
        /// </summary>
        Expendable = 1,
        /// <summary>
        /// 装备
        /// </summary>
        Equip = 2,
        /// <summary>
        /// 碎片
        /// </summary>
        Fragment = 3,
        /// <summary>
        /// 材料
        /// </summary>
        Material = 4,
        /// <summary>
        /// 任务
        /// </summary>
        Task = 5,
    }

} 

