
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LuBan.Runtime;
using SimpleJSON;


namespace cfg.l10n
{
    public partial class TbPatchDemo
    {
        private readonly System.Collections.Generic.Dictionary<int, l10n.PatchDemo> _dataMap;
        private readonly System.Collections.Generic.List<l10n.PatchDemo> _dataList;
        
        public TbPatchDemo(JSONNode jsonNode)
        {
            _dataMap = new System.Collections.Generic.Dictionary<int, l10n.PatchDemo>();
            _dataList = new System.Collections.Generic.List<l10n.PatchDemo>();
            
            foreach(JSONNode vNode in jsonNode.Children)
            {
                l10n.PatchDemo deserializeItem;
                { if(!vNode.IsObject) { throw new SerializationException(); }  deserializeItem = l10n.PatchDemo.DeserializePatchDemo(vNode);  }
                _dataList.Add(deserializeItem);
                _dataMap.Add(deserializeItem.Id, deserializeItem);
            }
        }
    
        public System.Collections.Generic.Dictionary<int, l10n.PatchDemo> DataMap 
        {
            get { return _dataMap; }
        }

        public System.Collections.Generic.List<l10n.PatchDemo> DataList 
        {
            get { return _dataList; }
        }
    
        public l10n.PatchDemo GetOrDefault(int key) 
        {  
            return _dataMap.TryGetValue(key, out var v) ? v : null;
        }
        
        public l10n.PatchDemo Get(int key) 
        { 
            return _dataMap[key];
        }
        
        public l10n.PatchDemo this[int key] 
        {
            get
            {
                return _dataMap[key];
            }
        }
    
        public void ResolveRef(Tables tables)
        {
            foreach(var value in _dataList)
            {
                value.ResolveRef(tables);
            }
        }
        
    }

}
