
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LuBan.Runtime;
using GameFrameX.Config;
using SimpleJSON;

namespace Hotfix.Config
{
    public sealed partial class PropItem : LuBan.Runtime.BeanBase
    {
        public PropItem(int Id, int Count) 
        {
            this.Id = Id;
            this.Count = Count;
            PostInit();
        }

        public PropItem(JSONNode _buf)
        {
            { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
            { if(!_buf["Count"].IsNumber) { throw new SerializationException(); }  Count = _buf["Count"]; }

            // Localization Key Begin
            // Localization Key End
            PostInit();
        }

        public static PropItem DeserializePropItem(JSONNode _buf)
        {
            return new PropItem(_buf);
        }

        /// <summary>
        /// 道具id
        /// </summary>
        public int Id { private set; get; }
        /// <summary>
        /// 道具数量
        /// </summary>
        public int Count { private set; get; }
        public const int __ID__ = -929329866;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
        }

        public void TranslateText(System.Func<string, string, string> translator)
        {
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Count:" + Count + ","
            + "}";
        }

        partial void PostInit();
    }
}
