
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LuBan.Runtime;
using SimpleJSON;


namespace cfg.tag
{
    public partial class TbTestTag
    {
        private readonly System.Collections.Generic.Dictionary<int, tag.TestTag> _dataMap;
        private readonly System.Collections.Generic.List<tag.TestTag> _dataList;
        
        public TbTestTag(JSONNode jsonNode)
        {
            _dataMap = new System.Collections.Generic.Dictionary<int, tag.TestTag>();
            _dataList = new System.Collections.Generic.List<tag.TestTag>();
            
            foreach(JSONNode vNode in jsonNode.Children)
            {
                tag.TestTag deserializeItem;
                { if(!vNode.IsObject) { throw new SerializationException(); }  deserializeItem = tag.TestTag.DeserializeTestTag(vNode);  }
                _dataList.Add(deserializeItem);
                _dataMap.Add(deserializeItem.Id, deserializeItem);
            }
        }
    
        public System.Collections.Generic.Dictionary<int, tag.TestTag> DataMap 
        {
            get { return _dataMap; }
        }

        public System.Collections.Generic.List<tag.TestTag> DataList 
        {
            get { return _dataList; }
        }
    
        public tag.TestTag GetOrDefault(int key) 
        {  
            return _dataMap.TryGetValue(key, out var v) ? v : null;
        }
        
        public tag.TestTag Get(int key) 
        { 
            return _dataMap[key];
        }
        
        public tag.TestTag this[int key] 
        {
            get
            {
                return _dataMap[key];
            }
        }
    
        public void ResolveRef(Tables tables)
        {
            foreach(var value in _dataList)
            {
                value.ResolveRef(tables);
            }
        }
        
    }

}
