
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LuBan.Runtime;
using SimpleJSON;


namespace cfg.test
{
    public partial class TbMultiRowTitle
    {
        private readonly System.Collections.Generic.Dictionary<int, test.MultiRowTitle> _dataMap;
        private readonly System.Collections.Generic.List<test.MultiRowTitle> _dataList;
        
        public TbMultiRowTitle(JSONNode jsonNode)
        {
            _dataMap = new System.Collections.Generic.Dictionary<int, test.MultiRowTitle>();
            _dataList = new System.Collections.Generic.List<test.MultiRowTitle>();
            
            foreach(JSONNode vNode in jsonNode.Children)
            {
                test.MultiRowTitle deserializeItem;
                { if(!vNode.IsObject) { throw new SerializationException(); }  deserializeItem = test.MultiRowTitle.DeserializeMultiRowTitle(vNode);  }
                _dataList.Add(deserializeItem);
                _dataMap.Add(deserializeItem.Id, deserializeItem);
            }
        }
    
        public System.Collections.Generic.Dictionary<int, test.MultiRowTitle> DataMap 
        {
            get { return _dataMap; }
        }

        public System.Collections.Generic.List<test.MultiRowTitle> DataList 
        {
            get { return _dataList; }
        }
    
        public test.MultiRowTitle GetOrDefault(int key) 
        {  
            return _dataMap.TryGetValue(key, out var v) ? v : null;
        }
        
        public test.MultiRowTitle Get(int key) 
        { 
            return _dataMap[key];
        }
        
        public test.MultiRowTitle this[int key] 
        {
            get
            {
                return _dataMap[key];
            }
        }
    
        public void ResolveRef(Tables tables)
        {
            foreach(var value in _dataList)
            {
                value.ResolveRef(tables);
            }
        }
        
    }

}
