
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LuBan.Runtime;
using SimpleJSON;


namespace cfg.test
{
    public partial class TbTestRef
    {
        private readonly System.Collections.Generic.Dictionary<int, test.TestRef> _dataMap;
        private readonly System.Collections.Generic.List<test.TestRef> _dataList;
        
        public TbTestRef(JSONNode jsonNode)
        {
            _dataMap = new System.Collections.Generic.Dictionary<int, test.TestRef>();
            _dataList = new System.Collections.Generic.List<test.TestRef>();
            
            foreach(JSONNode vNode in jsonNode.Children)
            {
                test.TestRef deserializeItem;
                { if(!vNode.IsObject) { throw new SerializationException(); }  deserializeItem = test.TestRef.DeserializeTestRef(vNode);  }
                _dataList.Add(deserializeItem);
                _dataMap.Add(deserializeItem.Id, deserializeItem);
            }
        }
    
        public System.Collections.Generic.Dictionary<int, test.TestRef> DataMap 
        {
            get { return _dataMap; }
        }

        public System.Collections.Generic.List<test.TestRef> DataList 
        {
            get { return _dataList; }
        }
    
        public test.TestRef GetOrDefault(int key) 
        {  
            return _dataMap.TryGetValue(key, out var v) ? v : null;
        }
        
        public test.TestRef Get(int key) 
        { 
            return _dataMap[key];
        }
        
        public test.TestRef this[int key] 
        {
            get
            {
                return _dataMap[key];
            }
        }
    
        public void ResolveRef(Tables tables)
        {
            foreach(var value in _dataList)
            {
                value.ResolveRef(tables);
            }
        }
        
    }

}
