
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LuBan.Runtime;
using SimpleJSON;


namespace cfg.test
{
    public partial class TbTestString
    {
        private readonly System.Collections.Generic.Dictionary<string, test.TestString> _dataMap;
        private readonly System.Collections.Generic.List<test.TestString> _dataList;
        
        public TbTestString(JSONNode jsonNode)
        {
            _dataMap = new System.Collections.Generic.Dictionary<string, test.TestString>();
            _dataList = new System.Collections.Generic.List<test.TestString>();
            
            foreach(JSONNode vNode in jsonNode.Children)
            {
                test.TestString deserializeItem;
                { if(!vNode.IsObject) { throw new SerializationException(); }  deserializeItem = test.TestString.DeserializeTestString(vNode);  }
                _dataList.Add(deserializeItem);
                _dataMap.Add(deserializeItem.Id, deserializeItem);
            }
        }
    
        public System.Collections.Generic.Dictionary<string, test.TestString> DataMap 
        {
            get { return _dataMap; }
        }

        public System.Collections.Generic.List<test.TestString> DataList 
        {
            get { return _dataList; }
        }
    
        public test.TestString GetOrDefault(string key) 
        {  
            return _dataMap.TryGetValue(key, out var v) ? v : null;
        }
        
        public test.TestString Get(string key) 
        { 
            return _dataMap[key];
        }
        
        public test.TestString this[string key] 
        {
            get
            {
                return _dataMap[key];
            }
        }
    
        public void ResolveRef(Tables tables)
        {
            foreach(var value in _dataList)
            {
                value.ResolveRef(tables);
            }
        }
        
    }

}
