
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LuBan.Runtime;
using SimpleJSON;


namespace cfg.test
{
    public partial class TbNotIndexList
    {
        private readonly System.Collections.Generic.List<test.NotIndexList> _dataList;
    
    
        public TbNotIndexList(JSONNode _buf)
        {
            _dataList = new System.Collections.Generic.List<test.NotIndexList>();
            
            foreach(JSONNode _ele in _buf.Children)
            {
                test.NotIndexList vNode;
                { if(!_ele.IsObject) { throw new SerializationException(); }  vNode = test.NotIndexList.DeserializeNotIndexList(_ele);  }
                _dataList.Add(vNode);
            }
        }
    
        public System.Collections.Generic.List<test.NotIndexList> DataList => _dataList;
    
        
        public void ResolveRef(Tables tables)
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef(tables);
            }
        }
    }

}
