
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LuBan.Runtime;
using GameFrameX.Config;
using SimpleJSON;

namespace Hotfix.Config.Tables
{
    public sealed partial class SoundsConfig : LuBan.Runtime.BeanBase
    {
        public SoundsConfig(int Id, string GroupName, string Path, string Title, string CharacterName) 
        {
            this.Id = Id;
            this.GroupName = GroupName;
            this.Path = Path;
            this.Title = Title;
            this.CharacterName = CharacterName;
            PostInit();
        }

        public SoundsConfig(JSONNode _buf)
        {
            { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
            { if(!_buf["groupName"].IsString) { throw new SerializationException(); }  GroupName = _buf["groupName"]; }
            { if(!_buf["path"].IsString) { throw new SerializationException(); }  Path = _buf["path"]; }
            { if(!_buf["title"].IsString) { throw new SerializationException(); }  Title = _buf["title"]; }
            { if(!_buf["characterName"].IsString) { throw new SerializationException(); }  CharacterName = _buf["characterName"]; }

            // Localization Key Begin
            Title_Localization_Key = Title;
            CharacterName_Localization_Key = CharacterName;
            // Localization Key End
            PostInit();
        }

        public static SoundsConfig DeserializeSoundsConfig(JSONNode _buf)
        {
            return new Tables.SoundsConfig(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public int Id { private set; get; }
        /// <summary>
        /// 声音所属组
        /// </summary>
        public string GroupName { private set; get; }
        /// <summary>
        /// 声音所在的路径
        /// </summary>
        public string Path { private set; get; }
        /// <summary>
        /// 声音标题Key
        /// </summary>
        public string Title { private set; get; }
        /// <summary>
        /// 声音标题Key 的多语言Key
        /// </summary>
        private readonly string Title_Localization_Key;
        public string CharacterName { private set; get; }
        private readonly string CharacterName_Localization_Key;
        public const int __ID__ = 4070031;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
            
            
            
        }

        public void TranslateText(System.Func<string, string, string> translator)
        {
            Title = translator(Title_Localization_Key, Title);
            CharacterName = translator(CharacterName_Localization_Key, CharacterName);
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "groupName:" + GroupName + ","
            + "path:" + Path + ","
            + "title:" + Title + ","
            + "characterName:" + CharacterName + ","
            + "}";
        }

        partial void PostInit();
    }
}
